import type { Metadata } from "next";
import {Poppins} from 'next/font/google'
import "./globals.css";
import Navbar from "@/Components/Layouts/Navbar/Navbar";


const poppins = Poppins({
  weight:['400','500','600','700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme='light'>
      <body
        className={`${poppins.variable} font-sans antialiased bg-base-100 flex flex-col min-h-screen`}
      >
        <header>
          <Navbar />
        </header>
       <main className="flex-1 bg-gray-100">
         {children}
       </main>
      </body>
    </html>
  );
}
